### PR TITLE
Add support of armeabi-v7a architecture

### PR DESCRIPTION
**Pull request by dmitvitalii**
- Support armeabi-v7a CPUs
- Use different libs for different architectures, choose from directories
- Fix an issue with hashrate: show middle value if max value is not available.

### CODE REVIEW

**Comment by bobbieltd** [comment]
Great thank you. Does it support Monero v7 ?

**Comment by dmitvitalii** [comment]
In this library the "cryptonight" algorithm is hardcoded.

If [xmrig](https://github.com/xmrig/xmrig) supports V7 (as far as I understood they do), the MoneroMiner can be fixed that way, but I didn't test it.

**Comment by bobbieltd** [comment]
If you compile new xmrig , it will switch and mine Monero v7 automatically (“algo” is till “cryptonight”, hard coded is not problem).

**Comment by bobbieltd** [comment]
I can not disable donation with your 32 bit xmrig.

**Comment by dmitvitalii** [comment]
They are disabled by default: [config.json](https://github.com/upost/MoneroMiner/blob/master/app/src/main/assets/config.json)

**Pull request merged**
